# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Qg-Qc Group"
title:              "QG-QC Group at CHEP, IISc"
description:        "description"


# URL
url:                https://chepgravitygroup.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  #- name:           "abstracts"
  #  href:           "/abstracts"
  - name:           "more"
    href:           "/more"
  #- name:           "lab teachings"
  #  href:           "/presentations"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
